all:
  children:
    rke2_cluster:
      children:
        rke2_servers:
          hosts:
            rke2_server0:
              ansible_host: 10.0.2.2
              ansible_user: root
              ansible_ssh_private_key_file: id_rsa
              vars:
                node_labels:
                  - name=server0
        rke2_agents:
          hosts:
            rke2_agent0:
              ansible_host: 10.0.2.3
              ansible_user: root
              ansible_ssh_private_key_file: id_rsa
              vars:
                node_labels:
                  - name=agent0
            rke2_agent1:
              ansible_host: 10.0.2.4
              ansible_user: root
              ansible_ssh_private_key_file: id_rsa
              vars:
                node_labels:
                  - name=agent1